name: Run Daily Arxiv on Schedule
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  schedule: # Trigger on a schedule
    - cron: "0 5 * * 1-5"  # This runs every weekday at 5 am (UTC).
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: "1"

permissions:
  contents: write
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies (if applicable)
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run Python script (retieve arxiv)
        run: |
          cd scripts
          python 1_arxiv_daily_rss.py

      - name: Run Python script (retrieve embeddings)
        run: |
          cd scripts
          python 2_gemini_daily_embeddings.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Configure git user (optional)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add and commit changes
        run: |
          git add .
          git commit -m "Push from GitHub Actions"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}